import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import { BarChart3, Boxes, ClipboardList, LogOut, Menu, PackageSearch, ShoppingBag, Truck } from "lucide-react";
import type { ReactNode } from "react";
import { useAuth } from "@/lib/auth";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet";

const vendorLinks = [{ to: "/vendor/products" as const, label: "My Products", icon: Boxes }, { to: "/vendor/orders" as const, label: "Incoming Orders", icon: ClipboardList }, { to: "/vendor/sales" as const, label: "Sales", icon: BarChart3 }];
const customerLinks = [{ to: "/shop" as const, label: "Browse Products", icon: PackageSearch }, { to: "/my-orders" as const, label: "My Orders", icon: ShoppingBag }];

function Navigation({ close }: { close?: () => void }) { const { session } = useAuth(); const path = useRouterState({ select: (s) => s.location.pathname }); const links = session?.role === "vendor" ? vendorLinks : customerLinks; return <nav className="grid gap-1">{links.map(({ to, label, icon: Icon }) => <Link key={to} to={to} onClick={close} className={cn("relative flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition", path === to ? "bg-sidebar-accent text-sidebar-accent-foreground before:absolute before:left-0 before:top-2 before:bottom-2 before:w-1 before:rounded-r before:bg-highlight [&>svg]:text-highlight" : "text-sidebar-muted hover:bg-sidebar-accent/60 hover:text-sidebar-foreground")}><Icon className="size-4"/>{label}</Link>)}</nav>; }
function Brand({ dark = true }: { dark?: boolean }) { return <div className="flex items-center gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-highlight text-highlight-foreground"><Truck className="size-5"/></div><div className="min-w-0"><p className={cn("truncate font-semibold", dark ? "text-sidebar-foreground" : "text-foreground")}>Supply Chain</p><p className={cn("text-xs", dark ? "text-sidebar-muted" : "text-muted-foreground")}>Operations system</p></div></div>; }
function UserBlock() { const { session, signOut } = useAuth(); const navigate = useNavigate(); return <div className="border-t border-sidebar-border pt-4"><div className="mb-3 min-w-0"><p className="truncate text-sm font-semibold text-sidebar-foreground">{session?.name}</p><p className="text-xs capitalize text-sidebar-muted">{session?.role} portal</p>{session?.access_token.startsWith("demo-") && <span className="mt-2 inline-block rounded-full bg-highlight/20 px-2 py-0.5 text-[11px] font-semibold text-highlight">Demo mode · sample data</span>}</div><Button variant="sidebar" className="w-full justify-start" onClick={() => { signOut(); void navigate({ to: "/login", replace: true }); }}><LogOut/>Log out</Button></div>; }
export function AppShell({ children }: { children: ReactNode }) { const { session, ready } = useAuth(); const navigate = useNavigate(); if (!ready) return <div className="min-h-screen bg-background"/>; if (!session) { void navigate({ to: "/login", replace: true }); return null; } return <div className="min-h-screen bg-background lg:grid lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="fixed inset-y-0 left-0 hidden w-60 flex-col bg-sidebar p-5 lg:flex"><Brand/><div className="mt-8"><p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-widest text-sidebar-muted">{session.role} portal</p><Navigation/></div><div className="mt-auto"><UserBlock/></div></aside><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-background/95 px-4 backdrop-blur lg:hidden"><Brand dark={false}/><Sheet><SheetTrigger asChild><Button variant="outline" size="icon" aria-label="Open navigation"><Menu/></Button></SheetTrigger><SheetContent side="left" className="flex w-72 flex-col bg-sidebar"><SheetTitle className="sr-only">Navigation</SheetTitle><Brand/><div className="mt-8"><Navigation/></div><div className="mt-auto"><UserBlock/></div></SheetContent></Sheet></header><main className="min-w-0 lg:col-start-2"><div className="mx-auto max-w-[1480px] space-y-7 p-4 sm:p-6 lg:p-8">{children}</div></main></div>; }
export function RoleGate({ role, children }: { role: "vendor" | "customer"; children: ReactNode }) { const { session, ready } = useAuth(); const navigate = useNavigate(); if (!ready) return null; if (!session) { void navigate({ to: "/login", replace: true }); return null; } if (session.role !== role) { void navigate({ to: session.role === "vendor" ? "/vendor/products" : "/shop", replace: true }); return null; } return <AppShell>{children}</AppShell>; }