import type { ReactNode } from "react";
import { AlertCircle, Box, LoaderCircle, Search } from "lucide-react";
import { cn } from "@/lib/utils";
import type { OrderStatus } from "@/lib/api";

export function PageHeader({ title, description, action }: { title: string; description: string; action?: ReactNode }) {
  return <header className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4"><div className="min-w-0"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-accent-foreground"><span className="h-1 w-5 rounded-full bg-highlight"/>Workspace</p><h1 className="mt-1 text-2xl font-semibold text-foreground sm:text-3xl">{title}</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">{description}</p></div>{action && <div className="shrink-0">{action}</div>}</header>;
}
export function StatusBadge({ status }: { status: OrderStatus }) { return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold", status === "PENDING" && "bg-warning-soft text-warning", status === "ACCEPTED" && "bg-success-soft text-success", status === "REJECTED" && "bg-destructive-soft text-destructive", status === "CANCELLED" && "bg-muted text-muted-foreground")}>{status}</span>; }
export function LoadingState({ label = "Loading workspace…" }: { label?: string }) { return <div className="grid min-h-52 place-items-center rounded-lg border border-border bg-card"><div className="text-center"><LoaderCircle className="mx-auto size-6 animate-spin text-primary"/><p className="mt-3 text-sm text-muted-foreground">{label}</p></div></div>; }
export function EmptyState({ title, description }: { title: string; description?: string }) { return <div className="grid min-h-52 place-items-center rounded-lg border border-dashed border-border bg-card p-8 text-center"><div><Box className="mx-auto size-7 text-muted-foreground"/><h3 className="mt-3 font-semibold">{title}</h3>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div></div>; }
export function ErrorState({ error, retry }: { error: Error; retry: () => void }) { return <div className="flex min-h-40 items-center justify-between gap-4 rounded-lg border border-destructive/20 bg-destructive-soft p-5"><div className="flex min-w-0 gap-3"><AlertCircle className="size-5 shrink-0 text-destructive"/><div><h3 className="font-semibold">Unable to load this page</h3><p className="mt-1 text-sm text-muted-foreground">{error.message}</p></div></div><button onClick={retry} className="shrink-0 text-sm font-semibold text-destructive underline">Try again</button></div>; }
export function SearchInput({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="relative block w-full sm:max-w-md"><span className="sr-only">{placeholder}</span><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="h-10 w-full rounded-md border border-input bg-background pl-9 pr-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15"/></label>; }
export function FilterTabs({ value, onChange, counts }: { value: string; onChange: (value: string) => void; counts: Record<string, number> }) { const items: Array<[string,string]> = [["ALL","All Orders"],["PENDING","Pending"],["ACCEPTED","Accepted"],["REJECTED","Rejected"],["CANCELLED","Cancelled"]]; return <div className="flex gap-1 overflow-x-auto border-b border-border" role="tablist">{items.map(([key,label]) => <button key={key} role="tab" aria-selected={value === key} onClick={() => onChange(key)} className={cn("shrink-0 border-b-2 px-3 py-2.5 text-sm font-medium transition", value === key ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground")}>{label} <span className={cn("ml-1.5 rounded-full px-1.5 py-0.5 text-xs", value === key ? "bg-highlight text-highlight-foreground" : "bg-muted")}>{counts[key] ?? 0}</span></button>)}</div>; }
export function Field({ label, error, children }: { label: string; error?: string | undefined; children: ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium"><span>{label}</span>{children}{error && <span className="text-xs font-normal text-destructive">{error}</span>}</label>; }
export function formatCurrency(value: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(value); }
export function formatDateTime(value: string) { const date = new Date(value); return { date: new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(date), time: new Intl.DateTimeFormat("en-IN", { timeStyle: "short" }).format(date) }; }