-- ============================================================================
-- Multi-Vendor Supply Chain Management System
-- COMPLETE SUPABASE SETUP SCRIPT (all in one)
-- ============================================================================
-- Paste this entire script into the Supabase SQL Editor and click RUN.
-- It drops and rebuilds the schema, then loads the demo data.
--
-- This file is generated by concatenating, in order:
--   schema.sql (DROP section only), tables.sql, constraints.sql,
--   functions.sql, views.sql, seed.sql
-- so it can never disagree with the individual files. If you change one of
-- those files, rebuild this one the same way.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- STEP 1: CLEAN SLATE
-- ----------------------------------------------------------------------------
DROP VIEW  IF EXISTS vw_vendor_product_sales CASCADE;
DROP VIEW  IF EXISTS vw_order_details        CASCADE;
DROP VIEW  IF EXISTS vw_available_products   CASCADE;

DROP TABLE IF EXISTS orders    CASCADE;
DROP TABLE IF EXISTS products  CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS vendors   CASCADE;

DROP TYPE  IF EXISTS order_status CASCADE;

DROP FUNCTION IF EXISTS place_order(INTEGER, INTEGER, INTEGER)          CASCADE;
DROP FUNCTION IF EXISTS place_order(INTEGER, INTEGER, INTEGER, TEXT, VARCHAR) CASCADE;
DROP FUNCTION IF EXISTS accept_order(INTEGER, INTEGER)                  CASCADE;
DROP FUNCTION IF EXISTS reject_order(INTEGER, INTEGER)                  CASCADE;
DROP FUNCTION IF EXISTS cancel_order(INTEGER, INTEGER, TEXT)            CASCADE;
DROP FUNCTION IF EXISTS update_product_price(INTEGER, INTEGER, NUMERIC) CASCADE;
DROP FUNCTION IF EXISTS delete_product(INTEGER, INTEGER)                CASCADE;
DROP FUNCTION IF EXISTS restock_product(INTEGER, INTEGER, INTEGER)      CASCADE;
DROP FUNCTION IF EXISTS customer_cancel_order(INTEGER, INTEGER)         CASCADE;
DROP FUNCTION IF EXISTS trg_products_set_updated_at()                   CASCADE;
DROP FUNCTION IF EXISTS trg_check_email_unique_across_roles()           CASCADE;


-- ----------------------------------------------------------------------------
-- STEP 2: TABLES  (tables.sql)
-- ----------------------------------------------------------------------------
-- =========================================================
-- Multi-Vendor Supply Chain Management System
-- 02. TABLES  (PostgreSQL / Supabase)
-- =========================================================
-- Four entities only: vendors, customers, products, orders.
-- Foreign keys, CHECKs and UNIQUEs are added separately in
-- constraints.sql so the ALTER TABLE syntax is visible.
-- =========================================================

-- Controlled set of order states. An enum type is used instead of
-- several boolean flags (is_accepted / is_rejected / ...) so an order
-- can only ever be in exactly one state.
DROP TYPE IF EXISTS order_status CASCADE;
CREATE TYPE order_status AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED');

-- ---------------------------------------------------------
-- vendors : a supplier who owns products and decides on orders
-- ---------------------------------------------------------
CREATE TABLE vendors (
    vendor_id     SERIAL       PRIMARY KEY,
    company_name  VARCHAR(150) NOT NULL,
    email         VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------
-- customers : a buyer who browses products and places orders
-- ---------------------------------------------------------
CREATE TABLE customers (
    customer_id   SERIAL       PRIMARY KEY,
    full_name     VARCHAR(150) NOT NULL,
    email         VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------
-- products : owned by exactly one vendor (Vendor 1 : N Product)
-- ---------------------------------------------------------
-- quantity is the vendor's own stock. It is decremented ONLY when the
-- vendor accepts an order (see accept_order() in functions.sql).
-- is_active supports soft deletion: a product referenced by historical
-- orders is hidden rather than physically removed.
CREATE TABLE products (
    product_id   SERIAL         PRIMARY KEY,
    vendor_id    INTEGER        NOT NULL,
    product_name VARCHAR(150)   NOT NULL,
    price        NUMERIC(10, 2) NOT NULL,
    quantity     INTEGER        NOT NULL DEFAULT 0,
    is_active    BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------
-- orders : one customer ordering one product
-- ---------------------------------------------------------
-- unit_price is a deliberate price snapshot: it records what the product
-- cost at the moment of ordering. It is NOT redundant with products.price,
-- because the vendor may change the price later and the order must keep
-- its historical value.
--
-- The vendor is intentionally NOT stored here. It is reached through
-- products.vendor_id, which avoids a transitive dependency (3NF).
CREATE TABLE orders (
    order_id            SERIAL         PRIMARY KEY,
    customer_id         INTEGER        NOT NULL,
    product_id          INTEGER        NOT NULL,
    quantity            INTEGER        NOT NULL,
    unit_price          NUMERIC(10, 2) NOT NULL,
    status              order_status    NOT NULL DEFAULT 'PENDING',
    cancellation_reason TEXT,
    shipping_address    TEXT,
    contact_phone       VARCHAR(25),
    ordered_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    decided_at          TIMESTAMPTZ
);

-- ----------------------------------------------------------------------------
-- STEP 3: CONSTRAINTS AND INDEXES  (constraints.sql)
-- ----------------------------------------------------------------------------
-- =========================================================
-- 03. CONSTRAINTS & INDEXES  (PostgreSQL / Supabase)
-- =========================================================
-- Added with ALTER TABLE so every constraint is explicit and named.
-- =========================================================

-- ---------------------------------------------------------
-- UNIQUE : an email identifies exactly one account
-- ---------------------------------------------------------
ALTER TABLE vendors   ADD CONSTRAINT uq_vendors_email   UNIQUE (email);
ALTER TABLE customers ADD CONSTRAINT uq_customers_email UNIQUE (email);

-- ---------------------------------------------------------
-- FOREIGN KEYS
-- ---------------------------------------------------------
-- products.vendor_id -> vendors.vendor_id
-- ON DELETE CASCADE: removing a vendor removes their catalogue.
ALTER TABLE products
    ADD CONSTRAINT fk_products_vendor
    FOREIGN KEY (vendor_id) REFERENCES vendors (vendor_id)
    ON DELETE CASCADE;

-- orders.customer_id -> customers.customer_id
-- ON DELETE RESTRICT: a customer with order history cannot be deleted.
ALTER TABLE orders
    ADD CONSTRAINT fk_orders_customer
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
    ON DELETE RESTRICT;

-- orders.product_id -> products.product_id
-- ON DELETE RESTRICT is the key referential-integrity decision: a product
-- that appears in any order can never be physically deleted, so historical
-- order records can never be orphaned. Vendors "delete" such a product by
-- soft-deleting it (is_active = FALSE) instead.
ALTER TABLE orders
    ADD CONSTRAINT fk_orders_product
    FOREIGN KEY (product_id) REFERENCES products (product_id)
    ON DELETE RESTRICT;

-- ---------------------------------------------------------
-- CHECK constraints
-- ---------------------------------------------------------
ALTER TABLE products
    ADD CONSTRAINT chk_products_price_non_negative CHECK (price >= 0);

ALTER TABLE products
    ADD CONSTRAINT chk_products_quantity_non_negative CHECK (quantity >= 0);

ALTER TABLE products
    ADD CONSTRAINT chk_products_name_not_blank CHECK (length(btrim(product_name)) > 0);

-- An order must always be for at least one unit.
ALTER TABLE orders
    ADD CONSTRAINT chk_orders_quantity_positive CHECK (quantity > 0);

ALTER TABLE orders
    ADD CONSTRAINT chk_orders_unit_price_non_negative CHECK (unit_price >= 0);

-- Business rule 7: a cancellation reason is mandatory for, and only
-- meaningful on, a CANCELLED order. One CHECK enforces both directions,
-- so a cancellation can never be recorded without a stored reason.
ALTER TABLE orders
    ADD CONSTRAINT chk_orders_cancellation_reason CHECK (
        (status = 'CANCELLED' AND cancellation_reason IS NOT NULL
                              AND length(btrim(cancellation_reason)) > 0)
        OR
        (status <> 'CANCELLED' AND cancellation_reason IS NULL)
    );

-- A decision timestamp exists exactly when the order has left PENDING.
ALTER TABLE orders
    ADD CONSTRAINT chk_orders_decided_at CHECK (
        (status = 'PENDING' AND decided_at IS NULL)
        OR
        (status <> 'PENDING' AND decided_at IS NOT NULL)
    );

-- ---------------------------------------------------------
-- Cross-table email uniqueness
-- ---------------------------------------------------------
-- UNIQUE only works within one table, so a trigger stops the same email
-- being registered as both a vendor and a customer.
CREATE OR REPLACE FUNCTION trg_check_email_unique_across_roles()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_TABLE_NAME = 'vendors' THEN
        IF EXISTS (SELECT 1 FROM customers WHERE email = NEW.email) THEN
            RAISE EXCEPTION 'Email % is already registered as a customer', NEW.email;
        END IF;
    ELSE
        IF EXISTS (SELECT 1 FROM vendors WHERE email = NEW.email) THEN
            RAISE EXCEPTION 'Email % is already registered as a vendor', NEW.email;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_vendors_email_unique
    BEFORE INSERT OR UPDATE OF email ON vendors
    FOR EACH ROW EXECUTE FUNCTION trg_check_email_unique_across_roles();

CREATE TRIGGER trg_customers_email_unique
    BEFORE INSERT OR UPDATE OF email ON customers
    FOR EACH ROW EXECUTE FUNCTION trg_check_email_unique_across_roles();

-- ---------------------------------------------------------
-- INDEXES
-- ---------------------------------------------------------
-- A vendor may not list the same product name twice, but a soft-deleted
-- name is freed up for re-use, so the unique index is partial.
CREATE UNIQUE INDEX uq_products_vendor_name_active
    ON products (vendor_id, lower(btrim(product_name)))
    WHERE is_active;

-- Supports "list my products" and the customer catalogue join.
CREATE INDEX idx_products_vendor    ON products (vendor_id);

-- Supports the customer's case-insensitive product-name search.
CREATE INDEX idx_products_name_lower ON products (lower(product_name));

-- Supports "my orders" (customer) and the vendor's incoming-order queue.
CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE INDEX idx_orders_product  ON orders (product_id);
CREATE INDEX idx_orders_status   ON orders (status);

-- ----------------------------------------------------------------------------
-- STEP 4: FUNCTIONS AND TRIGGERS  (functions.sql)
-- ----------------------------------------------------------------------------
-- =========================================================
-- 04. FUNCTIONS & TRIGGERS  (PostgreSQL / Supabase)
-- =========================================================
-- All order/inventory state changes go through these functions.
-- A PL/pgSQL function runs inside a single transaction, so each one
-- either completes fully or leaves the database untouched -- the
-- inventory can never be decremented without the order also moving
-- to ACCEPTED, and vice versa.
--
-- Every function a vendor can invoke takes p_vendor_id and checks
-- ownership itself, so authorisation is enforced in the database and
-- not only in the API layer.
--
-- Lock ordering is always  orders -> products  to avoid deadlocks.
-- =========================================================

-- ---------------------------------------------------------
-- TRIGGER: keep products.updated_at accurate
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_products_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION trg_products_set_updated_at();


-- ---------------------------------------------------------
-- place_order : customer places an order
-- ---------------------------------------------------------
-- Business rules 4 and 5 (plus optional shipping address and contact phone):
--   * the requested quantity must not exceed the available quantity
--   * the available quantity is NOT touched here -- placing an order
--     only records intent. Stock moves on acceptance.
-- SELECT ... FOR UPDATE locks the product row so two customers cannot
-- both pass the availability check against the same last units.
CREATE OR REPLACE FUNCTION place_order(
    p_customer_id      INTEGER,
    p_product_id       INTEGER,
    p_quantity         INTEGER,
    p_shipping_address TEXT    DEFAULT NULL,
    p_contact_phone    VARCHAR DEFAULT NULL
) RETURNS INTEGER AS $$
DECLARE
    v_available INTEGER;
    v_price     NUMERIC(10, 2);
    v_active    BOOLEAN;
    v_order_id  INTEGER;
BEGIN
    IF p_quantity IS NULL OR p_quantity <= 0 THEN
        RAISE EXCEPTION 'Order quantity must be at least 1.';
    END IF;

    SELECT quantity, price, is_active
      INTO v_available, v_price, v_active
      FROM products
     WHERE product_id = p_product_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Product not found.';
    END IF;

    IF NOT v_active THEN
        RAISE EXCEPTION 'This product is no longer available.';
    END IF;

    IF v_available = 0 THEN
        RAISE EXCEPTION 'This product is out of stock.';
    END IF;

    IF p_quantity > v_available THEN
        RAISE EXCEPTION 'Only % units are currently available.', v_available;
    END IF;

    INSERT INTO orders (
        customer_id, product_id, quantity, unit_price, status,
        shipping_address, contact_phone
    )
    VALUES (
        p_customer_id, p_product_id, p_quantity, v_price, 'PENDING',
        nullif(btrim(p_shipping_address), ''), nullif(btrim(p_contact_phone), '')
    )
    RETURNING order_id INTO v_order_id;

    RETURN v_order_id;
END;
$$ LANGUAGE plpgsql;


-- ---------------------------------------------------------
-- accept_order : vendor accepts -- the only place stock decreases
-- ---------------------------------------------------------
-- Business rule 5. Availability is re-checked at acceptance time,
-- because the vendor may have accepted other orders in the meantime.
CREATE OR REPLACE FUNCTION accept_order(
    p_order_id  INTEGER,
    p_vendor_id INTEGER
) RETURNS VOID AS $$
DECLARE
    v_status     order_status;
    v_product_id INTEGER;
    v_ordered    INTEGER;
    v_owner_id   INTEGER;
    v_available  INTEGER;
BEGIN
    SELECT o.status, o.product_id, o.quantity
      INTO v_status, v_product_id, v_ordered
      FROM orders o
     WHERE o.order_id = p_order_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order not found.';
    END IF;

    SELECT vendor_id, quantity
      INTO v_owner_id, v_available
      FROM products
     WHERE product_id = v_product_id
     FOR UPDATE;

    IF v_owner_id <> p_vendor_id THEN
        RAISE EXCEPTION 'This order belongs to another vendor.';
    END IF;

    IF v_status <> 'PENDING' THEN
        RAISE EXCEPTION 'Only a pending order can be accepted (this one is %).', v_status;
    END IF;

    IF v_available < v_ordered THEN
        RAISE EXCEPTION 'Not enough stock to accept this order: % ordered, % available.',
                        v_ordered, v_available;
    END IF;

    UPDATE products
       SET quantity = quantity - v_ordered
     WHERE product_id = v_product_id;

    UPDATE orders
       SET status = 'ACCEPTED', decided_at = now()
     WHERE order_id = p_order_id;
END;
$$ LANGUAGE plpgsql;


-- ---------------------------------------------------------
-- reject_order : vendor rejects -- stock is NOT touched
-- ---------------------------------------------------------
-- Business rule 6.
CREATE OR REPLACE FUNCTION reject_order(
    p_order_id  INTEGER,
    p_vendor_id INTEGER
) RETURNS VOID AS $$
DECLARE
    v_status   order_status;
    v_owner_id INTEGER;
BEGIN
    SELECT o.status, p.vendor_id
      INTO v_status, v_owner_id
      FROM orders o
      JOIN products p ON p.product_id = o.product_id
     WHERE o.order_id = p_order_id
     FOR UPDATE OF o;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order not found.';
    END IF;

    IF v_owner_id <> p_vendor_id THEN
        RAISE EXCEPTION 'This order belongs to another vendor.';
    END IF;

    IF v_status <> 'PENDING' THEN
        RAISE EXCEPTION 'Only a pending order can be rejected (this one is %).', v_status;
    END IF;

    UPDATE orders
       SET status = 'REJECTED', decided_at = now()
     WHERE order_id = p_order_id;
END;
$$ LANGUAGE plpgsql;


-- ---------------------------------------------------------
-- cancel_order : vendor cancels, with a mandatory stored reason
-- ---------------------------------------------------------
-- Business rules 7 and 8. A PENDING or an already ACCEPTED order can be
-- cancelled. Cancelling an ACCEPTED order returns its units to stock,
-- because those units were deducted when it was accepted.
CREATE OR REPLACE FUNCTION cancel_order(
    p_order_id  INTEGER,
    p_vendor_id INTEGER,
    p_reason    TEXT
) RETURNS VOID AS $$
DECLARE
    v_status     order_status;
    v_product_id INTEGER;
    v_ordered    INTEGER;
    v_owner_id   INTEGER;
BEGIN
    IF p_reason IS NULL OR length(btrim(p_reason)) = 0 THEN
        RAISE EXCEPTION 'A cancellation reason is required.';
    END IF;

    SELECT o.status, o.product_id, o.quantity
      INTO v_status, v_product_id, v_ordered
      FROM orders o
     WHERE o.order_id = p_order_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order not found.';
    END IF;

    SELECT vendor_id INTO v_owner_id
      FROM products
     WHERE product_id = v_product_id
     FOR UPDATE;

    IF v_owner_id <> p_vendor_id THEN
        RAISE EXCEPTION 'This order belongs to another vendor.';
    END IF;

    IF v_status NOT IN ('PENDING', 'ACCEPTED') THEN
        RAISE EXCEPTION 'A % order cannot be cancelled.', v_status;
    END IF;

    -- Return the units that acceptance had already deducted.
    IF v_status = 'ACCEPTED' THEN
        UPDATE products
           SET quantity = quantity + v_ordered
         WHERE product_id = v_product_id;
    END IF;

    UPDATE orders
       SET status = 'CANCELLED',
           cancellation_reason = btrim(p_reason),
           decided_at = now()
     WHERE order_id = p_order_id;
END;
$$ LANGUAGE plpgsql;


-- ---------------------------------------------------------
-- update_product_price : vendor edits their own product price
-- ---------------------------------------------------------
-- Business rule 2. The ownership test lives in the WHERE clause, so a
-- vendor touching another vendor's product matches zero rows.
CREATE OR REPLACE FUNCTION update_product_price(
    p_product_id INTEGER,
    p_vendor_id  INTEGER,
    p_price      NUMERIC
) RETURNS VOID AS $$
DECLARE
    v_rows INTEGER;
BEGIN
    IF p_price IS NULL OR p_price < 0 THEN
        RAISE EXCEPTION 'Price cannot be negative.';
    END IF;

    UPDATE products
       SET price = p_price
     WHERE product_id = p_product_id
       AND vendor_id  = p_vendor_id
       AND is_active;

    GET DIAGNOSTICS v_rows = ROW_COUNT;
    IF v_rows = 0 THEN
        RAISE EXCEPTION 'Product not found in your catalogue.';
    END IF;
END;
$$ LANGUAGE plpgsql;


-- ---------------------------------------------------------
-- delete_product : vendor removes their own product
-- ---------------------------------------------------------
-- Business rule 2, without destroying order history. A product that has
-- never been ordered is deleted outright; one that appears in any order
-- is soft-deleted, so the FK from orders stays valid and the historical
-- record survives. Returns 'deleted' or 'archived' so the UI can report
-- which of the two happened.
CREATE OR REPLACE FUNCTION delete_product(
    p_product_id INTEGER,
    p_vendor_id  INTEGER
) RETURNS TEXT AS $$
DECLARE
    v_owner_id    INTEGER;
    v_order_count INTEGER;
BEGIN
    SELECT vendor_id INTO v_owner_id
      FROM products
     WHERE product_id = p_product_id
       AND is_active
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Product not found in your catalogue.';
    END IF;

    IF v_owner_id <> p_vendor_id THEN
        RAISE EXCEPTION 'You can only delete your own products.';
    END IF;

    SELECT count(*) INTO v_order_count
      FROM orders
     WHERE product_id = p_product_id;

    IF v_order_count = 0 THEN
        DELETE FROM products WHERE product_id = p_product_id;
        RETURN 'deleted';
    END IF;

    UPDATE products
       SET is_active = FALSE
     WHERE product_id = p_product_id;
    RETURN 'archived';
END;
$$ LANGUAGE plpgsql;


-- ---------------------------------------------------------
-- restock_product : vendor replenishes stock for an active product
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION restock_product(
    p_product_id     INTEGER,
    p_vendor_id      INTEGER,
    p_added_quantity INTEGER
) RETURNS INTEGER AS $$
DECLARE
    v_owner_id  INTEGER;
    v_new_stock INTEGER;
BEGIN
    IF p_added_quantity IS NULL OR p_added_quantity <= 0 THEN
        RAISE EXCEPTION 'Restock quantity must be at least 1.';
    END IF;

    SELECT vendor_id
      INTO v_owner_id
      FROM products
     WHERE product_id = p_product_id
       AND is_active
       FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Product % not found in your catalogue.', p_product_id;
    END IF;

    IF v_owner_id <> p_vendor_id THEN
        RAISE EXCEPTION 'You can only restock your own products.';
    END IF;

    UPDATE products
       SET quantity = quantity + p_added_quantity
     WHERE product_id = p_product_id
     RETURNING quantity INTO v_new_stock;

    RETURN v_new_stock;
END;
$$ LANGUAGE plpgsql;


-- ---------------------------------------------------------
-- customer_cancel_order : customer cancels their own PENDING order
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION customer_cancel_order(
    p_order_id    INTEGER,
    p_customer_id INTEGER
) RETURNS VOID AS $$
DECLARE
    v_customer_id INTEGER;
    v_status      order_status;
BEGIN
    SELECT customer_id, status
      INTO v_customer_id, v_status
      FROM orders
     WHERE order_id = p_order_id
       FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order % not found.', p_order_id;
    END IF;

    IF v_customer_id <> p_customer_id THEN
        RAISE EXCEPTION 'You can only cancel your own orders.';
    END IF;

    IF v_status <> 'PENDING' THEN
        RAISE EXCEPTION 'Only pending orders can be cancelled by customer (current status: %).', v_status;
    END IF;

    UPDATE orders
       SET status = 'CANCELLED',
           cancellation_reason = 'Cancelled by customer',
           decided_at = now()
     WHERE order_id = p_order_id;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- STEP 5: VIEWS  (views.sql)
-- ----------------------------------------------------------------------------
-- =========================================================
-- 05. VIEWS  (PostgreSQL / Supabase)
-- =========================================================
-- Three views, each backing a real screen in the application:
-- the customer catalogue, the order lists, and the vendor sales chart.
-- =========================================================

-- ---------------------------------------------------------
-- vw_available_products : the customer-facing catalogue
-- ---------------------------------------------------------
-- Requirement 5.1 / 8: only products that can actually be ordered are
-- listed, so soft-deleted and out-of-stock rows are filtered out here
-- rather than in the frontend. The supplier name is resolved through the
-- foreign key, never stored on the product row.
CREATE OR REPLACE VIEW vw_available_products AS
SELECT p.product_id,
       p.product_name,
       p.price,
       p.quantity AS available_quantity,
       v.vendor_id,
       v.company_name AS supplier_name,
       p.created_at,
       p.updated_at
  FROM products p
  JOIN vendors  v ON v.vendor_id = p.vendor_id
 WHERE p.is_active
   AND p.quantity > 0;


-- ---------------------------------------------------------
-- vw_order_details : one row per order, fully resolved
-- ---------------------------------------------------------
-- A four-table JOIN that both dashboards read: the vendor's incoming
-- queue filters it by vendor_id, the customer's history by customer_id.
-- line_total is computed, never stored.
CREATE OR REPLACE VIEW vw_order_details AS
SELECT o.order_id,
       o.status,
       o.quantity,
       o.unit_price,
       (o.quantity * o.unit_price) AS line_total,
       o.cancellation_reason,
       o.ordered_at,
       o.decided_at,
       c.customer_id,
       c.full_name    AS customer_name,
       p.product_id,
       p.product_name,
       p.is_active    AS product_is_active,
       v.vendor_id,
       v.company_name AS supplier_name,
       o.shipping_address,
       o.contact_phone,
       p.quantity     AS current_stock
  FROM orders    o
  JOIN customers c ON c.customer_id = o.customer_id
  JOIN products  p ON p.product_id  = o.product_id
  JOIN vendors   v ON v.vendor_id   = p.vendor_id;


-- ---------------------------------------------------------
-- vw_vendor_product_sales : sales analytics per product
-- ---------------------------------------------------------
-- Requirement 15. Only ACCEPTED orders count as sales, so a rejected or
-- cancelled order never inflates revenue. Aggregation lives in the view,
-- which keeps the chart endpoint down to a single filtered SELECT.
CREATE OR REPLACE VIEW vw_vendor_product_sales AS
SELECT p.vendor_id,
       p.product_id,
       p.product_name,
       count(o.order_id)                       AS orders_accepted,
       COALESCE(sum(o.quantity), 0)            AS units_sold,
       COALESCE(sum(o.quantity * o.unit_price), 0) AS revenue
  FROM products p
  LEFT JOIN orders o
         ON o.product_id = p.product_id
        AND o.status = 'ACCEPTED'
 GROUP BY p.vendor_id, p.product_id, p.product_name;

-- ----------------------------------------------------------------------------
-- STEP 6: DEMO DATA  (seed.sql, every account uses the password password123)
-- ----------------------------------------------------------------------------
-- =========================================================
-- 06. SEED DATA  (PostgreSQL / Supabase)  -- optional
-- =========================================================
-- Demo data for a presentation: three vendors, three customers, a
-- catalogue, and orders spread across all four statuses and several
-- weeks so the sales charts have something real to draw.
--
-- Every demo account logs in with the password:   password123
-- The stored value is a real bcrypt hash of that password -- the
-- application never sees or stores a plaintext password.
--
--   psql "$DATABASE_URL" -f database/seed.sql
-- =========================================================

-- Start from empty. TRUNCATE ... CASCADE also clears orders, and
-- RESTART IDENTITY resets the SERIAL counters so the ids below are
-- predictable.
TRUNCATE orders, products, customers, vendors RESTART IDENTITY CASCADE;


-- ---------------------------------------------------------
-- Vendors  (vendor_id 1..3)
-- ---------------------------------------------------------
INSERT INTO vendors (company_name, email, password_hash) VALUES
('ABC Electronics',  'abc@vendor.com',    '$2b$10$m24vYDrZzTlWA5KZGHyRfeO.mtLV6RhuddIjoQJSgOc0aed79mTZG'),
('Sharma Textiles',  'sharma@vendor.com', '$2b$10$m24vYDrZzTlWA5KZGHyRfeO.mtLV6RhuddIjoQJSgOc0aed79mTZG'),
('Verma Packaging',  'verma@vendor.com',  '$2b$10$m24vYDrZzTlWA5KZGHyRfeO.mtLV6RhuddIjoQJSgOc0aed79mTZG');


-- ---------------------------------------------------------
-- Customers  (customer_id 1..3)
-- ---------------------------------------------------------
INSERT INTO customers (full_name, email, password_hash) VALUES
('Rahul Mehta',   'rahul@customer.com',  '$2b$10$m24vYDrZzTlWA5KZGHyRfeO.mtLV6RhuddIjoQJSgOc0aed79mTZG'),
('Priya Nair',    'priya@customer.com',  '$2b$10$m24vYDrZzTlWA5KZGHyRfeO.mtLV6RhuddIjoQJSgOc0aed79mTZG'),
('TechMart Pvt',  'orders@techmart.com', '$2b$10$m24vYDrZzTlWA5KZGHyRfeO.mtLV6RhuddIjoQJSgOc0aed79mTZG');


-- ---------------------------------------------------------
-- Products  (product_id 1..8)
-- ---------------------------------------------------------
-- quantity here is the STARTING stock, before any order was accepted.
-- The reconciliation step at the bottom of this file deducts the
-- accepted units, so the seeded data obeys the same inventory rule the
-- application enforces.
INSERT INTO products (vendor_id, product_name, price, quantity) VALUES
(1, 'Laptop',            45000.00,  20),
(1, 'Bluetooth Speaker',   899.00, 150),
(1, 'USB-C Cable',         120.00, 500),
(1, 'Wireless Mouse',      649.00,   0),   -- out of stock: hidden from the catalogue
(2, 'Cotton T-Shirt',      250.00, 300),
(2, 'Denim Jacket',       1899.00,  45),
(3, 'Corrugated Box',       18.50, 900),
(3, 'Bubble Wrap Roll',    340.00,  60);


-- ---------------------------------------------------------
-- Orders  (order_id 1..13)
-- ---------------------------------------------------------
-- Inserted directly with backdated timestamps so the "orders over time"
-- chart spans several weeks. The CHECK constraints still apply: a
-- non-PENDING order must carry decided_at, and only a CANCELLED order
-- may carry a cancellation_reason.
--
-- unit_price is the price at order time, which is why it is stored on
-- the order rather than read from products.
INSERT INTO orders (customer_id, product_id, quantity, unit_price, status, cancellation_reason, ordered_at, decided_at) VALUES
-- accepted (these are the only rows that count as revenue)
(1, 1, 2, 45000.00, 'ACCEPTED', NULL, now() - INTERVAL '34 days', now() - INTERVAL '33 days'),
(3, 3, 100,  120.00, 'ACCEPTED', NULL, now() - INTERVAL '28 days', now() - INTERVAL '28 days'),
(2, 5, 40,   250.00, 'ACCEPTED', NULL, now() - INTERVAL '21 days', now() - INTERVAL '20 days'),
(1, 2, 5,    899.00, 'ACCEPTED', NULL, now() - INTERVAL '14 days', now() - INTERVAL '14 days'),
(3, 7, 250,   18.50, 'ACCEPTED', NULL, now() - INTERVAL '9 days',  now() - INTERVAL '9 days'),
(2, 6, 3,   1899.00, 'ACCEPTED', NULL, now() - INTERVAL '5 days',  now() - INTERVAL '4 days'),

-- rejected: inventory was never touched
(2, 1, 10, 45000.00, 'REJECTED', NULL, now() - INTERVAL '17 days', now() - INTERVAL '16 days'),

-- cancelled by the vendor, with the stored reason both dashboards show.
-- One is included for each vendor, so whichever demo account is used the
-- cancellation reason is visible on that vendor's own dashboard too.
(1, 6, 2,   1899.00, 'CANCELLED', 'Product damaged during quality inspection.', now() - INTERVAL '11 days', now() - INTERVAL '10 days'),
(3, 8, 5,    340.00, 'CANCELLED', 'Supplier stock failed quality check; replacement batch delayed.', now() - INTERVAL '6 days', now() - INTERVAL '6 days'),
(2, 2, 4,    899.00, 'CANCELLED', 'Unit failed final inspection; awaiting a replacement batch.', now() - INTERVAL '8 days', now() - INTERVAL '7 days'),

-- still awaiting a vendor decision: must NOT have moved any stock
(2, 2, 8,    899.00, 'PENDING',  NULL, now() - INTERVAL '2 days',  NULL),
(1, 3, 25,   120.00, 'PENDING',  NULL, now() - INTERVAL '1 day',   NULL),
(3, 5, 60,   250.00, 'PENDING',  NULL, now() - INTERVAL '3 hours', NULL);


-- ---------------------------------------------------------
-- Reconcile inventory with the accepted orders
-- ---------------------------------------------------------
-- Business rules 5 and 6 in one statement: subtract the units of every
-- ACCEPTED order, and nothing for PENDING, REJECTED or CANCELLED ones.
-- (A cancelled order that had been accepted would have had its units
-- returned, so it nets to zero either way.)
UPDATE products p
   SET quantity = p.quantity - sold.units
  FROM (SELECT product_id, sum(quantity) AS units
          FROM orders
         WHERE status = 'ACCEPTED'
         GROUP BY product_id) AS sold
 WHERE p.product_id = sold.product_id;


-- ---------------------------------------------------------
-- Sanity check the seed
-- ---------------------------------------------------------
SELECT 'vendors' AS table_name, count(*) FROM vendors
UNION ALL SELECT 'customers', count(*) FROM customers
UNION ALL SELECT 'products',  count(*) FROM products
UNION ALL SELECT 'orders',    count(*) FROM orders;

SELECT p.product_name, p.quantity AS stock_on_hand
  FROM products p ORDER BY p.product_id;
