import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, MapPin, Phone } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { api, type CustomerOrder, type OrderStatus, type VendorOrder } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { EmptyState, ErrorState, Field, FilterTabs, LoadingState, PageHeader, SearchInput, StatusBadge, formatCurrency, formatDateTime } from "@/components/system";

type AnyOrder = VendorOrder | CustomerOrder;
const textareaClass = "min-h-28 resize-y rounded-md border border-input bg-background px-3 py-2 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15";
function countsFor(orders: AnyOrder[]) { return orders.reduce<Record<string,number>>((acc,o)=>{acc["ALL"]=(acc["ALL"]??0)+1;acc[o.status]=(acc[o.status]??0)+1;return acc;},{ALL:0,PENDING:0,ACCEPTED:0,REJECTED:0,CANCELLED:0}); }

export function VendorOrdersPage() {
  const client=useQueryClient(); const query=useQuery({queryKey:["vendor-orders"],queryFn:api.getVendorOrders}); const [filter,setFilter]=useState("ALL"); const [search,setSearch]=useState(""); const [selected,setSelected]=useState<VendorOrder|null>(null); const [action,setAction]=useState<"reject"|"cancel"|null>(null); const [reason,setReason]=useState("");
  const orders=query.data??[]; const visible=useMemo(()=>orders.filter(o=>(filter==="ALL"||o.status===filter)&&`${o.order_id} ${o.customer_name} ${o.product_name}`.toLowerCase().includes(search.toLowerCase())),[orders,filter,search]);
  const update=useMutation({mutationFn:({order,next,reasonText}:{order:VendorOrder;next:"accept"|"reject"|"cancel";reasonText?:string})=>api.updateVendorOrder(order.order_id,next,reasonText),onSuccess:(_result,vars)=>{toast.success(vars.next==="accept"?"ORDER RECEIVED":vars.next==="reject"?"ORDER REJECTED":"ORDER CANCELLED");setSelected(null);setAction(null);setReason("");void client.invalidateQueries({queryKey:["vendor-orders"]});},onError:(e)=>toast.error(e.message)});
  const pending=countsFor(orders)["PENDING"] ?? 0;
  return <><PageHeader title="Incoming Orders" description={pending?`${pending} order${pending===1?"":"s"} awaiting your decision.`:"Review and manage orders placed against your products."}/><div className="grid gap-4"><SearchInput value={search} onChange={setSearch} placeholder="Search by customer, product, or order #..."/><FilterTabs value={filter} onChange={setFilter} counts={countsFor(orders)}/></div>{query.isLoading?<LoadingState label="Loading incoming orders…"/>:query.error?<ErrorState error={query.error} retry={()=>void query.refetch()}/>:!orders.length?<EmptyState title="No orders yet."/>:!visible.length?<EmptyState title="No orders match the current filter or search."/>:<div className="grid gap-4">{visible.map(o=><OrderCard key={o.order_id} order={o} vendor actions={<>{o.status==="PENDING"&&<><Button size="sm" disabled={o.quantity>o.current_stock||update.isPending} onClick={()=>update.mutate({order:o,next:"accept"})}>Accept</Button><Button size="sm" variant="outline" onClick={()=>{setSelected(o);setAction("reject")}}>Reject</Button></>}{(o.status==="PENDING"||o.status==="ACCEPTED")&&<Button size="sm" variant="ghost" onClick={()=>{setSelected(o);setAction("cancel")}}>Cancel</Button>}</>}/>)}</div>}<Dialog open={Boolean(selected)} onOpenChange={(open)=>!open&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{action==="reject"?`Reject order #${selected?.order_id}?`:`Cancel order #${selected?.order_id}?`}</DialogTitle><DialogDescription>{action==="reject"?"Stock will remain unchanged.":selected?.status==="ACCEPTED"?"Accepted units will be returned to inventory.":"The cancellation reason is stored with the order and shown to the customer."}</DialogDescription></DialogHeader>{selected&&<div className="rounded-md bg-muted p-4 text-sm"><strong>{selected.quantity} × {selected.product_name}</strong><p className="mt-1 text-muted-foreground">Customer: {selected.customer_name}</p></div>}{action==="cancel"&&<Field label="Reason for cancellation" error={reason.length>0&&reason.trim().length<3?"Enter at least 3 characters.":undefined}><textarea autoFocus className={textareaClass} minLength={3} maxLength={500} placeholder="Product damaged during quality inspection." value={reason} onChange={(e)=>setReason(e.target.value)}/><span className="text-right text-xs text-muted-foreground">{reason.length}/500</span></Field>}<DialogFooter><Button variant="outline" onClick={()=>setSelected(null)}>Keep Order</Button><Button variant="destructive" disabled={update.isPending||!selected||(action==="cancel"&&(reason.trim().length<3||reason.length>500))} onClick={()=>selected&&action&&update.mutate({order:selected,next:action,...(reason.trim()?{reasonText:reason.trim()}:{})})}>{update.isPending?"Working…":action==="reject"?"Reject Order":"Cancel Order"}</Button></DialogFooter></DialogContent></Dialog></>;
}

export function CustomerOrdersPage() {
  const client=useQueryClient(); const query=useQuery({queryKey:["customer-orders"],queryFn:api.getCustomerOrders}); const [filter,setFilter]=useState("ALL"); const [selected,setSelected]=useState<CustomerOrder|null>(null); const orders=[...(query.data??[])].sort((a,b)=>new Date(b.ordered_at).getTime()-new Date(a.ordered_at).getTime()); const visible=orders.filter(o=>filter==="ALL"||o.status===filter);
  const cancel=useMutation({mutationFn:(order:CustomerOrder)=>api.cancelCustomerOrder(order.order_id),onSuccess:()=>{toast.success("ORDER CANCELLED");setSelected(null);void client.invalidateQueries({queryKey:["customer-orders"]});},onError:(e)=>toast.error(e.message)});
  return <><PageHeader title="My Orders" description="Track every order and its current supplier decision."/><FilterTabs value={filter} onChange={setFilter} counts={countsFor(orders)}/>{query.isLoading?<LoadingState label="Loading your orders…"/>:query.error?<ErrorState error={query.error} retry={()=>void query.refetch()}/>:!orders.length?<EmptyState title="No orders yet."/>:!visible.length?<EmptyState title="No orders match the current filter."/>:<div className="grid gap-4">{visible.map(o=><OrderCard key={o.order_id} order={o} actions={o.status==="PENDING"?<Button size="sm" variant="outline" onClick={()=>setSelected(o)}>Cancel</Button>:undefined}/>)}</div>}<Dialog open={Boolean(selected)} onOpenChange={(open)=>!open&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>Cancel order #{selected?.order_id}?</DialogTitle><DialogDescription>Are you sure you want to cancel your order for {selected?.quantity} × {selected?.product_name} from {selected?.supplier_name}?</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setSelected(null)}>Keep Order</Button><Button variant="destructive" disabled={cancel.isPending||!selected} onClick={()=>selected&&cancel.mutate(selected)}>{cancel.isPending?"Cancelling…":"Cancel Order"}</Button></DialogFooter></DialogContent></Dialog></>;
}

function OrderCard({order,actions,vendor=false}:{order:AnyOrder;actions?:React.ReactNode;vendor?:boolean}) { const when=formatDateTime(order.ordered_at); const vendorOrder=vendor?order as VendorOrder:null; const customerOrder=!vendor?order as CustomerOrder:null; const person=vendorOrder?.customer_name??customerOrder?.supplier_name; const insufficient=Boolean(vendorOrder&&order.status==="PENDING"&&order.quantity>vendorOrder.current_stock); return <article className="rounded-lg border border-border bg-card p-5 shadow-sm"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-base font-semibold">Order #{order.order_id}</h2><StatusBadge status={order.status}/></div><p className="mt-1 text-sm text-muted-foreground">{order.product_name} · {vendor?"Customer":"Supplier"}: {person}</p></div><div className="shrink-0 text-right"><p className="font-semibold">{formatCurrency(order.line_total)}</p><p className="text-xs text-muted-foreground">{when.date} · {when.time}</p></div></div><div className="mt-4 grid gap-3 border-y border-border py-4 text-sm sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Quantity</p><p className="font-semibold">{order.quantity} units</p></div><div><p className="text-xs text-muted-foreground">Unit price</p><p className="font-semibold">{formatCurrency(order.unit_price)}</p></div>{vendorOrder&&<div><p className="text-xs text-muted-foreground">Current stock</p><p className="font-semibold">{vendorOrder.current_stock} units</p></div>}</div>{insufficient&&<div className="mt-4 flex gap-3 rounded-md border border-warning/25 bg-warning-soft p-3 text-sm"><AlertTriangle className="size-5 shrink-0 text-warning"/><div><strong>Insufficient stock</strong><p className="text-muted-foreground">Need: {order.quantity} · Stock: {vendorOrder?.current_stock}. Restock before accepting.</p></div></div>}<div className="mt-4 grid gap-2 text-sm text-muted-foreground">{order.shipping_address&&<p className="flex gap-2"><MapPin className="mt-0.5 size-4 shrink-0"/>{order.shipping_address}</p>}{order.contact_phone&&<p className="flex gap-2"><Phone className="mt-0.5 size-4 shrink-0"/>{order.contact_phone}</p>}{order.cancellation_reason&&<div className="rounded-md bg-destructive-soft p-3 text-foreground"><strong>Cancellation reason</strong><p className="mt-1 text-muted-foreground">{order.cancellation_reason}</p></div>}</div>{actions&&<div className="mt-4 flex flex-wrap justify-end gap-2">{actions}</div>}</article>; }